name: PR Generate Labels
'on':
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize
    paths:
    - .github/**
    - ci-scripts/**
    - cn/**
    - cwf/**
    - docs/**
    - dp/**
    - example/**
    - experimental/**
    - feg/**
    - lte/**
    - nms/**
    - openwrt/**
    - orc8r/**
    - protos/**
    - scripts/**
    - secrets/**
    - show-tech/**
    - third_party/**
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  AutoLabelPR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
      with:
        script: "let newCompLbls = new Set(); // Set of new label strings\n\n// Fetch\
          \ files modified in the PR\nconst pulledFiles = await github.rest.pulls.listFiles({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  pull_number:\
          \ context.issue.number,\n});\n\n// Identify new component labels based on\
          \ the files modified in the PR\nfor (const f of pulledFiles['data']) {\n\
          \ switch (true) {\n  case /^ci-scripts\\/.*/.test(f.filename):\n  case /^\\\
          .github\\/workflows\\/.*/.test(f.filename):\n  case /^third_party\\/build\\\
          /.*/.test(f.filename):\n  case /^orc8r\\/tools\\/packer\\/.*/.test(f.filename):\n\
          \  case /^orc8r\\/cloud\\/deploy\\/bare-metal\\/.*/.test(f.filename):\n\
          \  case /^orc8r\\/cloud\\/deploy\\/bare-metal-ansible\\/.*/.test(f.filename):\n\
          \  case /^lte\\/gateway\\/docker\\/.*/.test(f.filename):\n  case /^lte\\\
          /gateway\\/release\\/.*/.test(f.filename):\n  case /^lte\\/gateway\\/Vagrantfile/.test(f.filename):\n\
          \  case /^cwf\\/gateway\\/Vagrantfile/.test(f.filename):\n    console.log(\"\
          file changed under CI component : \" + f['filename']);\n    newCompLbls.add(\"\
          component: ci\");\n    break;\n  case /^nms\\/.*/.test(f.filename):\n  \
          \  console.log(\"file changed under NMS component : \" + f['filename']);\n\
          \    newCompLbls.add(\"component: nms\");\n    break;\n  case /^cwf\\/.*/.test(f.filename):\n\
          \  case /^feg\\/radius\\/.*/.test(f.filename):\n    console.log(\"file changed\
          \ under CWF component : \" + f['filename']);\n    newCompLbls.add(\"component:\
          \ cwf\");\n    break;\n  case /^feg\\/.*/.test(f.filename):\n    console.log(\"\
          file changed under FEG component : \" + f['filename']);\n    newCompLbls.add(\"\
          component: feg\");\n    break;\n  case /^openwrt\\/.*/.test(f.filename):\n\
          \    console.log(\"file changed under OPENWRT component : \" + f['filename']);\n\
          \    newCompLbls.add(\"component: openwrt\");\n    break;\n  case /^lte\\\
          /gateway\\/.*/.test(f.filename):\n  case /^lte\\/protos\\/.*/.test(f.filename):\n\
          \  case /^orc8r\\/gateway\\/c\\/.*/.test(f.filename):\n  case /^third_party\\\
          /gtp_ovs\\/.*/.test(f.filename):\n    console.log(\"file changed under AGW\
          \ component : \" + f['filename']);\n    newCompLbls.add(\"component: agw\"\
          );\n    break;\n  case /.*\\/cloud\\/.*/.test(f.filename):\n  case /^\\\
          .golangci\\.yml/.test(f.filename):\n  case /^orc8r\\/.*/.test(f.filename):\n\
          \    console.log(\"file changed under ORC8R component : \" + f['filename']);\n\
          \    newCompLbls.add(\"component: orc8r\");\n    break;\n  case /^show-tech\\\
          /.*/.test(f.filename):\n    console.log(\"file changed under SHOW-TECH component\
          \ : \" + f['filename']);\n    newCompLbls.add(\"component: show-tech\");\n\
          \    break;\n  case /^docs\\/.*/.test(f.filename):\n    console.log(\"file\
          \ changed under DOCS: \" + f['filename']);\n    newCompLbls.add(\"component:\
          \ docs\");\n    break;\n  case /^dp\\/.*/.test(f.filename):\n    console.log(\"\
          file changed under DP component: \" + f['filename']);\n    newCompLbls.add(\"\
          component: dp\");\n    break;\n } // end of switch case\n} // end of for\
          \ loop\n\n\nconst curLblObjs = await github.rest.issues.listLabelsOnIssue({\n\
          \  issue_number: context.issue.number,\n  owner: context.repo.owner,\n \
          \ repo: context.repo.repo,\n});\n\n// Delete current component labels from\
          \ PR that are no more valid\nfor (const l of curLblObjs['data']) {\n  //console.log(\"\
          Current LabelName: \" + l['name'] + \" LabelDescription: \" + l['description']);\n\
          \  if(l['name'].startsWith(\"component: \"))  {\n    if(newCompLbls.has(l['name']))\
          \  {\n      newCompLbls.delete(l['name']);\n    }\n    else  {\n      github.rest.issues.removeLabel({\n\
          \        issue_number: context.issue.number,\n        owner: context.repo.owner,\n\
          \        repo: context.repo.repo,\n        name: l['name'],\n      });\n\
          \    }\n  } // end of if block\n} // end of for loop\n\nif( newCompLbls.size\
          \ == 0 )  {\n  console.log(\"No new component files changed in this PR:\
          \ \" + context.issue.number);\n}\nelse  {\n  let uniqLbls = Array.from(newCompLbls);\n\
          \  github.rest.issues.addLabels({\n    issue_number: context.issue.number,\n\
          \    owner: context.repo.owner,\n    repo: context.repo.repo,\n    labels:\
          \ uniqLbls,\n  });\n} // end of else block\n"
