name: PR Backport
'on':
  pull_request_target:
    types:
    - closed
    - labeled
jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    if: "github.event.pull_request.merged && contains(join(github.event.pull_request.labels.*.name,\
      \ ', '), 'apply-') && (\n  github.event.action == 'closed'\n  || (\n    github.event.action\
      \ == 'labeled'\n    && startsWith(github.event.label.name, 'apply-')\n  )\n\
      )\n"
    steps:
    - run: "echo '{\n  \"prTitle\": \"{commitMessages} [backport to {targetBranch}]\"\
        \n}' > .backportrc.json\n"
    - name: Backport Action
      uses: sqren/backport-github-action@f54e19901f2a57f8b82360f2490d47ee82ec82c6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        auto_backport_label_prefix: apply-
    - name: Info log
      if: ${{ success() }}
      run: cat /home/runner/.backport/backport.info.log
    - name: Debug log
      if: ${{ failure() }}
      run: cat /home/runner/.backport/backport.debug.log
