name: PR Check Codeowners
'on':
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    paths:
    - CODEOWNERS
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: GitHub CODEOWNERS Validator
      uses: mszostok/codeowners-validator@2f6e3bb39aa6837d7dcf8eff2de5d6c046d0c9a9
      with:
        checks: syntax,files,duppatterns
