name: PR Generate Comment On Workflow Failure
'on':
  workflow_run:
    workflows:
    - PR Check DCO
    - AGW Build & Format Python
    - Docs Lint & Check Generated Files In Sync
    types:
    - completed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha
    }}-${{ github.event.workflow.name }}
  cancel-in-progress: true
jobs:
  skip_check:
    name: Job to check if the workflow ${{ github.event.workflow.name }} can be skipped
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' ||  github.event.workflow_run.event
      == 'pull_request_target'
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - name: Download artifact
      uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
      with:
        script: "var artifacts = await github.rest.actions.listWorkflowRunArtifacts({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   run_id:\
          \ ${{github.event.workflow_run.id }},\n});\nvar matchArtifact = artifacts.data.artifacts.filter((artifact)\
          \ => {\n  return artifact.name == \"pr\"\n})[0];\nvar download = await github.rest.actions.downloadArtifact({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   artifact_id:\
          \ matchArtifact.id,\n   archive_format: 'zip',\n});\nvar fs = require('fs');\n\
          fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));\n"
    - run: unzip pr.zip
    - name: Check if the workflow is skipped
      id: skip_check
      uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
      with:
        script: "var fs = require('fs');\nvar skipFlag = fs.readFileSync('./skipped');\n\
          var rprFlag = fs.readFileSync('./is_reverted_pr');\nif( (skipFlag == 'true')\
          \ || (rprFlag == 'true') ) {\n  core.setOutput('should_skip', 'true');\n\
          \  //console.log(\"Skipping because should_skip=\" + skipFlag);\n}\nelse\
          \  {\n  core.setOutput('should_skip', 'false');\n  //console.log(\"NOT Skipping\
          \ because should_skip=\" + skipFlag);\n}\n"
  comment_pr:
    name: Comment on PR for check ${{ github.event.workflow.name }}
    needs: skip_check
    runs-on: ubuntu-latest
    if: needs.skip_check.outputs.should_skip == 'false'
    env:
      CHECK_GUIDELINE: '[Guide to the different CI checks and resolution guidelines](https://github.com/magma/magma/wiki/Contributing-Code#continuous-integration-ci--continuous-deployment-cd)'
      WORKFLOW_NAME: ${{ github.event.workflow.name }}
      WORKFLOW_STATUS: ${{ github.event.workflow_run.conclusion }}
    steps:
    - name: Download artifact
      uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
      with:
        script: "var artifacts = await github.rest.actions.listWorkflowRunArtifacts({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   run_id:\
          \ ${{github.event.workflow_run.id }},\n});\nvar matchArtifact = artifacts.data.artifacts.filter((artifact)\
          \ => {\n  return artifact.name == \"pr\"\n})[0];\nvar download = await github.rest.actions.downloadArtifact({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   artifact_id:\
          \ matchArtifact.id,\n   archive_format: 'zip',\n});\nvar fs = require('fs');\n\
          fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));\n"
    - run: unzip pr.zip
    - name: DCO comment message
      if: ${{ github.event.workflow.name == 'PR Check DCO' }}
      run: 'echo "Oops! Looks like you failed the \`PR Check DCO\`. Be sure to sign
        all your commits.

        ### Howto

        - [Magma guidelines on signing commits](https://github.com/magma/magma/wiki/Contributing-Code#signed-off-commits)

        - [About the \`signoff\` feature](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

        - [Howto: sign-off most-recent commit](https://stackoverflow.com/questions/13043357#answer-15667644)

        - [Howto: sign-off multiple past commits](https://gist.github.com/kwk/d70f20d17b18c4f3296d)

        - $CHECK_GUIDELINE" >> $GITHUB_WORKSPACE/msg

        '
    - name: Python format comment message
      if: ${{ github.event.workflow.name == 'AGW Build & Format Python' }}
      run: 'echo "Oops! Looks like you failed the \`AGW Build & Format Python\`.

        ### Howto

        - Instructions on running the formatter and linter locally are provided in
        the [format AGW doc](https://magma.github.io/magma/docs/lte/dev_unit_testing#format-python)

        - $CHECK_GUIDELINE" >> $GITHUB_WORKSPACE/msg

        '
    - name: Semantic PR comment message
      if: ${{ github.event.workflow.name == 'Semantic PR' }}
      run: 'echo "Oops! Looks like you failed the \`Semantic PR check\`.

        ### Howto

        - [Instructions on formatting your PR title](https://github.com/magma/magma/wiki/Contributing-Code#pull-request-and-commit-message-title-are-following-conventional-commits-format)

        - For PRs with only one commit, the commit message must also be semantic.
        See [Changing a commit message](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message)
        for a howto

        - $CHECK_GUIDELINE" >> $GITHUB_WORKSPACE/msg

        '
    - name: Markdown lint comment message
      if: ${{ github.event.workflow.name == 'Docs Lint & Check Generated Files In
        Sync' }}
      run: 'echo "Oops! Looks like you failed the \`Docs Lint & Check Generated Files
        In Sync\`.

        ### Howto

        - [Instructions on formatting your Markdown changes](https://github.com/magma/magma/wiki/Contributing-Documentation#precommit)

        - $CHECK_GUIDELINE" >> $GITHUB_WORKSPACE/msg

        '
    - name: Comment on PR
      uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
      with:
        script: "var fs = require('fs');\nvar isRevertedPR = fs.readFileSync('./is_reverted_pr');\n\
          if( isRevertedPR == 'true' ) {\n  console.log(\"PR is a reverted PR. So\
          \ exiting gracefully...\");\n  process.exit(0);\n}\nvar issue_number = Number(fs.readFileSync('./pr_number'));\n\
          const msg = fs.readFileSync('./msg',{encoding: 'utf8'})\n\nvar commentId\
          \ = 0;\nvar oldMsg = '';\nvar updMsg = '';\nvar newMsg = '';\n//var shortCommitId\
          \ = process.env.COMMIT_ID.substr(0,8);;\n\nconst commentsList = await github.rest.issues.listComments({\n\
          \                            owner: context.repo.owner,\n              \
          \              repo: context.repo.repo,\n                            issue_number:\
          \ issue_number,\n                          });\n\nfor (const c of commentsList['data'])\
          \ {\n  oldMsg = c.body;\n  if( oldMsg.includes('Oops! Looks like you failed\
          \ the `' + process.env.WORKFLOW_NAME) ) {\n      commentId = c.id;\n   \
          \   if( process.env.WORKFLOW_STATUS == 'failure' )  {\n          updMsg\
          \ = \":recycle: Updated: :x: The check is still failing the \" + process.env.WORKFLOW_NAME\
          \ + \" after the last commit.\";\n      }\n      else if( process.env.WORKFLOW_STATUS\
          \ == 'success' ) {\n          updMsg = \":recycle: Updated: :white_check_mark:\
          \ The check is passing the \" + process.env.WORKFLOW_NAME + \" after the\
          \ last commit.\";\n      }\n      newMsg = msg + \"\\n\\n\" + updMsg;\n\
          \      console.log(\"UPDATING comment=\" + newMsg);\n      github.rest.issues.updateComment({\n\
          \                    owner: context.repo.owner,\n                    repo:\
          \ context.repo.repo,\n                    comment_id: commentId,\n     \
          \               body: newMsg,\n                  });\n      break;\n  }\
          \ // end of if block\n} // end of for loop on commentsList\n\nif( (commentId\
          \ == 0) && (process.env.WORKFLOW_STATUS == 'failure') ) {\n  console.log(\"\
          CREATING comment=\" + msg);\n  github.rest.issues.createComment({\n    \
          \            issue_number: issue_number,\n                owner: context.repo.owner,\n\
          \                repo: context.repo.repo,\n                body: msg,\n\
          \              });\n}\n"
