name: PR Check DCO
'on':
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  reverted-pr-check:
    name: Reverted PR Check Job
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
    outputs:
      is_reverted_pr: ${{ steps.reverted_pr_check.outputs.is_reverted_pr }}
    steps:
    - name: Check if PR is a Reverted PR
      id: reverted_pr_check
      uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
      with:
        script: "if( process.env.PR_TITLE.startsWith('Revert') ) {\n  core.setOutput('is_reverted_pr',\
          \ 'true');\n}\nelse  {\n  core.setOutput('is_reverted_pr', 'false');\n}\n"
    - name: Save Reverted PR output
      if: always()
      run: 'mkdir -p ./pr

        echo -n ${{ steps.reverted_pr_check.outputs.is_reverted_pr }} > ./pr/is_reverted_pr

        echo -n "false" > ./pr/skipped

        '
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      if: always()
      with:
        name: reverted check pr
        path: pr/
  dco_check_job:
    needs: reverted-pr-check
    if: ${{ needs.reverted-pr-check.outputs.is_reverted_pr == 'false' }}
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
    - name: Get PR Commits
      id: get-pr-commits
      uses: tim-actions/get-pr-commits@c64db31d359214d244884dd68f971a110b29ab83
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Perform DCO Check
      uses: tim-actions/dco@f2279e6e62d5a7d9115b0cb8e837b777b1b02e21
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
    - name: Save PR number
      if: always()
      run: 'mkdir -p ./pr

        echo -n ${{ github.event.number }} > ./pr/pr_number

        '
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      if: always()
      with:
        name: dco check job pr
        path: pr/
