name: Docs Build & Deploy
'on':
  push:
    branches:
    - master
jobs:
  docusaurus-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: Export vars
      run: 'echo "DOCUSAURUS_URL=https://magma.github.io" >> $GITHUB_ENV

        echo "DOCUSAURUS_BASE_URL=/magma/" >> $GITHUB_ENV

        '
    - name: Setup docusaurus expected directory structure
      run: 'mv docs/docusaurus website/

        mv docs/readmes readmes/

        rm -rf docs/

        mv readmes/ docs/

        '
    - name: Deploying to GitHub Pages
      run: 'git config --global user.email "magma-docusaurus-bot@users.noreply.github.com"

        git config --global user.name "magma-docusaurus-bot"

        echo "machine github.com login magma-docusaurus-bot password ${{ secrets.DOCUSAURUS_GITHUB_TOKEN
        }}" > ~/.netrc

        cd website && yarn install

        CUSTOM_COMMIT_MESSAGE="[skip ci] Deploy website" GIT_USER=magma-docusaurus-bot
        yarn run publish-gh-pages

        # yamllint enable

        '
