name: Magma Check Helm Dependencies
'on':
  push:
    branches:
    - master
    - v1.*
  pull_request:
    branches:
    - master
    - v1.*
    types:
    - opened
    - reopened
    - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true
jobs:
  check_helm_chart_dependencies:
    env:
      MAGMA_ROOT: ${{ github.workspace }}
    runs-on: ubuntu-latest
    name: Check dependency of helm chart ${{ matrix.charts[0] }}
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: Check Orc8r
      run: "echo \"DIGEST=$(cat $MAGMA_ROOT/orc8r/cloud/helm/orc8r/Chart.lock | grep\
        \ digest | cut -d \":\" -f 2-3 | xargs)\" >> $GITHUB_ENV\nhelm dependency\
        \ update \"$MAGMA_ROOT/orc8r/cloud/helm/orc8r/\"\necho \"NEW_DIGEST=$(cat\
        \ $MAGMA_ROOT/orc8r/cloud/helm/orc8r/Chart.lock | grep digest | cut -d \"\
        :\" -f 2-3 | xargs)\" >> $GITHUB_ENV\nif [ \"$DIGEST\" != \"$NEW_DIGEST\"\
        \ ]; then\n  exit 1\nfi\n"
    - name: Check cwf-orc8r
      if: always()
      run: "echo \"DIGEST=$(cat $MAGMA_ROOT/cwf/cloud/helm/cwf-orc8r//Chart.lock |\
        \ grep digest | cut -d \":\" -f 2-3 | xargs)\" >> $GITHUB_ENV\nhelm dependency\
        \ update \"$MAGMA_ROOT/cwf/cloud/helm/cwf-orc8r/\"\necho \"NEW_DIGEST=$(cat\
        \ $MAGMA_ROOT/cwf/cloud/helm/cwf-orc8r//Chart.lock | grep digest | cut -d\
        \ \":\" -f 2-3 | xargs)\" >> $GITHUB_ENV\nif [ \"$DIGEST\" != \"$NEW_DIGEST\"\
        \ ]; then\n  exit 1\nfi\n"
    - name: Check lte-orc8r
      if: always()
      run: "echo \"DIGEST=$(cat $MAGMA_ROOT/lte/cloud/helm/lte-orc8r/Chart.lock |\
        \ grep digest | cut -d \":\" -f 2-3 | xargs)\" >> $GITHUB_ENV\nhelm dependency\
        \ update \"$MAGMA_ROOT/lte/cloud/helm/lte-orc8r/\"\necho \"NEW_DIGEST=$(cat\
        \ $MAGMA_ROOT/lte/cloud/helm/lte-orc8r/Chart.lock | grep digest | cut -d \"\
        :\" -f 2-3 | xargs)\" >> $GITHUB_ENV\nif [ \"$DIGEST\" != \"$NEW_DIGEST\"\
        \ ]; then\n  exit 1\nfi\n"
    - name: Check feg-orc8r
      if: always()
      run: "echo \"DIGEST=$(cat $MAGMA_ROOT/feg/cloud/helm/feg-orc8r/Chart.lock |\
        \ grep digest | cut -d \":\" -f 2-3 | xargs)\" >> $GITHUB_ENV\nhelm dependency\
        \ update \"$MAGMA_ROOT/feg/cloud/helm/feg-orc8r/\"\necho \"NEW_DIGEST=$(cat\
        \ $MAGMA_ROOT/feg/cloud/helm/feg-orc8r/Chart.lock | grep digest | cut -d \"\
        :\" -f 2-3 | xargs)\" >> $GITHUB_ENV\nif [ \"$DIGEST\" != \"$NEW_DIGEST\"\
        \ ]; then\n  exit 1\nfi"
