name: Orc8r Check Generated Files In Sync
'on':
  push:
    branches:
    - master
    - v1.*
  pull_request:
    branches:
    - master
    - v1.*
    types:
    - opened
    - reopened
    - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true
jobs:
  insync-checkin:
    name: insync checkin job
    runs-on: ubuntu-latest
    env:
      MAGMA_ROOT: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
      with:
        python-version: 3.8.10
    - name: Run build.py
      run: 'cd ${MAGMA_ROOT}/orc8r/cloud/docker

        python3 build.py --generate

        sudo chown -R $USER $MAGMA_ROOT/*

        git add .

        echo GIT_STATUS=$(git status) >> $GITHUB_ENV

        git status

        git diff-index --quiet HEAD'
