name: Magma Publish Go Package
'on':
  workflow_dispatch:
    inputs:
      version:
        description: Version to upload?
        default: 1.20.1
        required: true
env:
  GO_PACKAGE: go${{ inputs.version }}.linux-amd64.tar.gz
jobs:
  build_dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Download Go package
      run: curl -L https://go.dev/dl/$GO_PACKAGE -o $GO_PACKAGE
    - name: Set up JFrog CLI
      id: jfrog-setup
      if: ${{ env.JF_USER != '' && env.JF_PASSWORD != '' }}
      uses: jfrog/setup-jfrog-cli@d0a59b1cdaeeb16e65b5039fc92b8507337f1559
      env:
        JF_URL: https://linuxfoundation.jfrog.io/
        JF_USER: ${{ secrets.LF_JFROG_USERNAME }}
        JF_PASSWORD: ${{ secrets.LF_JFROG_PASSWORD }}
    - name: Publish Go package
      if: steps.jfrog-setup.conclusion == 'success'
      run: "jf rt upload \\\n  --recursive=false \\\n  --detailed-summary \\\n  $GO_PACKAGE\
        \ magma-blob/$GO_PACKAGE\n"
