name: PR Generate Hello
'on':
  pull_request_target:
    types:
    - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "var msg = `Thanks for opening a PR! :100:\n\n[A couple initial guidelines](https://github.com/magma/magma/wiki/Contributing-Code#commit-and-pull-request-guidelines)\n\
          - All commits must be signed off. This is enforced by [\\`PR DCO check\\\
          `](https://github.com/magma/magma/blob/master/.github/workflows/dco-check.yml).\n\
          - All PR titles must follow the semantic commits format. This is enforced\
          \ by [\\`PR Check Title Or Commit Message\\`](https://github.com/magma/magma/blob/master/.github/workflows/semantic-pr.yml).\n\
          \n### Howto\n- ***Reviews.*** The \"Reviewers\" listed for this PR are the\
          \ Magma maintainers who will shepherd it.\n- ***Checks.*** All required\
          \ CI checks must pass before merge.\n- ***Merge.*** Once approved and passing\
          \ CI checks, use the [\\`ready2merge\\`](https://github.com/magma/magma/labels/ready2merge)\
          \ label to indicate the maintainers can merge your PR.\n\n### More info\n\
          \nPlease take a moment to read through the Magma project's\n- [Contributing\
          \ Conventions](https://github.com/magma/magma/wiki/Contributing-Code-Conventions)\
          \ for norms around contributed code\n\nIf this is your first Magma PR, also\
          \ consider reading\n- [Developer Onboarding](https://github.com/magma/magma/wiki/Contributor-Guide)\
          \ for onboarding as a new Magma developer\n- [Development Workflow](https://github.com/magma/magma/wiki/Contributing-Code#developing-workflow)\
          \ for guidance on your first PR\n- [CI Checks](https://github.com/magma/magma/wiki/Contributing-Code#continuous-integration-ci--continuous-deployment-cd)\
          \ for points of contact for failing or flaky CI checks\n- [Code Review Process](https://github.com/magma/magma/wiki/Contributing-Code#code-review-process)\
          \ for information on requesting reviews and contacting maintainers`\n\n\
          github.rest.issues.createComment({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  body: msg,\n\
          })\n"
