name: PR Check Title Or Commit Message
'on':
  pull_request_target:
    types:
    - opened
    - reopened
    - edited
    - synchronize
    - ready_for_review
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  check-semantic-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@01d5fd8a8ebb9aafe902c40c53f0f4744f7381eb
      id: semantic-pr
      if: ${{ ! startsWith(github.event.pull_request.title, 'Revert ') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: 'feat

          fix

          docs

          style

          refactor

          perf

          test

          build

          ci

          chore

          revert

          '
        scopes: 'aaa_server

          agw

          amf

          ci

          cloud

          connectiond

          control_proxy

          csfb

          ctraced

          cwg

          deps

          deps-dev

          directoryd

          docusaurus

          dp

          eap

          eap_aka

          eap_sim

          enodebd

          envoy_controller

          eventd

          feg

          feg_hello

          feg_relay

          health

          lte

          magmad

          mme

          mobilityd

          monitord

          nms

          orc8r

          pipelined

          policydb

          radiusd

          redirectd

          redis

          s6a_proxy

          s8_proxy

          sctpd

          session_proxy

          sessiond

          smf

          smsd

          state

          subscriberdb

          swx_proxy

          td-agent-bit

          upf

          '
        requireScope: false
        wip: true
        validateSingleCommit: true
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      if: always()
    - uses: ./.github/workflows/composite/comment-on-pr
      if: always()
      env:
        check-type: Semantic PR check
        check-documentation: See [instructions on formatting your commit and pull
          request titles](https://github.com/magma/magma/wiki/Contributing-Code#pull-request-and-commit-message-title-are-following-conventional-commits-format).
      with:
        check-type: ${{ env.check-type }}
        check-documentation: ${{ env.check-documentation }}
        job-status: ${{ steps.semantic-pr.outcome }}
